name: sysinfo install in azure

on:
  push:
    branches:
      - avansat_main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r quickrequirements.txt
          pip freeze > requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      #- name: Upload artifact for deployment jobs
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: python-app
      #    path: |
      #      . 
      #      !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.clientidsecretname }}
          tenant-id: ${{ secrets.tenantidsecretname }}
          subscription-id: ${{ secrets.subscriptionidsecretname }}
    
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'sysinfov3'
          slot-name: 'Production'
          #publish-profile: ${{ secrets.SYSINFOV3 }}
